# Generated by Django 4.2.2 on 2023-07-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHora',models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(max_length=100)),
                ('comentario', models.CharField(max_length=1000)),
            ],
        ),
    ]
