# Generated by Django 4.2.2 on 2023-07-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuarios_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='codigo',
            field=models.CharField(default='', max_length=30),
        ),
    ]
