# Generated by Django 4.2.2 on 2023-07-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuarios_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='codigo',
            field=models.IntegerField(default='', max_length=30),
        ),
    ]
