# Generated by Django 4.2.2 on 2023-07-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_usuarios_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='codigo',
            field=models.IntegerField(default=0),
        ),
    ]
